include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    unused_local_variable: warning
  exclude:
    - '**/*.g.dart'

linter:
  rules:
    # General code quality
    - prefer_const_constructors
    - prefer_final_fields
    - prefer_is_empty
    - prefer_iterable_whereType
    - avoid_print
    - avoid_unnecessary_containers
    - avoid_redundant_argument_values
    - always_declare_return_types
    # - always_specify_types
    - unnecessary_getters_setters
    - unnecessary_new
    - unnecessary_this
    - avoid_annotating_with_dynamic

    # Formatting and readability
    - prefer_single_quotes
    - always_put_control_body_on_new_line
    - lines_longer_than_80_chars
    - avoid_function_literals_in_foreach_calls
    - avoid_returning_null
    - prefer_inlined_adds
    - avoid_empty_else
    - prefer_collection_literals
    - avoid_escaping_inner_quotes

    # Null safety
    - unnecessary_nullable_for_final_variable_declarations
    - prefer_null_aware_operators
    - avoid_null_checks_in_equality_operators

    # Performance and optimization
    - iterable_contains_unrelated_type
    
    - avoid_dynamic_calls
    - avoid_shadowing_type_parameters

